-- AlterTable
ALTER TABLE "transaction" ADD COLUMN     "fee" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "tt" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "ttc" DECIMAL(65,30) NOT NULL DEFAULT 0;
