import FormatTools from "@/shared/tools/formatTools";
import type { GenericListColumn } from "@/shared/types";
import type { NexusUpdateDto } from "@eu/types";

const nexusColumns: GenericListColumn<NexusUpdateDto>[] = [
  {
    key: "name",
    label: "Type",
    accessor: "name",
    kind: "text",
    fillRemainingSpace: true,
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 font-medium text-table-head-text",
  },
  {
    key: "nexusName",
    label: "NexusSubType",
    accessor: "nexusName",
    kind: "text",
    fillRemainingSpace: true,
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 font-medium text-table-head-text",
  },
  {
    key: "requestType",
    label: "Type",
    accessor: "nexusRequestType",
    kind: "text",
    fillRemainingSpace: true,
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 font-medium text-table-head-text",
  },
  {
    key: "itemCount",
    label: "Items",
    accessor: "itemCount",
    kind: "number",
    minWidth: 100,
    maxWidth: 100,
    align: "right",
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 justify-end font-medium text-table-body-text",
  },
  {
    key: "imageMissingCount",
    label: "Images KO",
    accessor: "imageMissingCount",
    kind: "number",
    minWidth: 100,
    maxWidth: 100,
    align: "right",
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 justify-end font-medium text-table-body-text",
  },
  {
    key: "changeCount",
    label: "Changes",
    accessor: "changeCount",
    kind: "number",
    minWidth: 100,
    maxWidth: 100,
    align: "right",
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 justify-end font-medium text-table-body-text",
  },
  {
    key: "createdAt",
    label: "Created",
    accessor: "createdAt",
    kind: "date",
    minWidth: 100,
    maxWidth: 100,
    align: "right",
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 justify-end font-medium text-table-body-text",
    value: (row) => FormatTools.dateFrShort(row.createdAt),
  },
  {
    key: "insertedAt",
    label: "Inserted",
    accessor: "insertedAt",
    kind: "date",
    minWidth: 100,
    maxWidth: 100,
    align: "right",
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 justify-end font-medium text-table-body-text",
    value: (row) => FormatTools.dateFrShort(row.insertedAt ?? row.createdAt),
  },
  {
    key: "updatedAt",
    label: "Updated",
    accessor: "updatedAt",
    kind: "date",
    minWidth: 100,
    maxWidth: 100,
    align: "right",
    headerCellClassName: "px-3",
    bodyCellClassName: "px-3 justify-end font-medium text-table-body-text",
    value: (row) => FormatTools.dateFrShort(row.updatedAt ?? row.createdAt),
  },
];

export { nexusColumns };
