import { defineConfig } from "orval";

export default defineConfig({
  entropia: {
    input: {
      target: "./src/api/openapi.json",
    },
    output: {
      client: "axios",
      mode: "split",
      target: "./src/api/generated/endpoints",
      schemas: "./src/api/generated/model",
      operationSchemas: "./src/api/generated/model/operations",
      clean: true,
      override: {
        useTypeOverInterfaces: true,
        header: (info) => [
          "Generated by orval from the Entropia Manager OpenAPI spec.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
        ],
      },
    },
  },
  entropiaZod: {
    input: {
      target: "./src/api/openapi.json",
    },
    output: {
      client: "zod",
      mode: "split",
      target: "./src/api/generated/zod",
      schemas: "./src/api/generated/zod/model",
      clean: true,
      override: {
        zod: {
          version: 4,
          variant: "classic",
          generateReusableSchemas: true,
          generateCompanionTypes: true,
        },
        header: (info) => [
          "Generated by orval from the Entropia Manager OpenAPI spec.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
        ],
      },
    },
  },
  entropiaReactQuery: {
    input: {
      target: "./src/api/openapi.json",
    },
    output: {
      client: "react-query",
      httpClient: "axios",
      mode: "split",
      target: "./src/api/generated/react-query",
      schemas: "./src/api/generated/react-query/model",
      clean: true,
      override: {
        mutator: {
          path: "./src/api/mutator/customInstance.ts",
          name: "customInstance",
        },
        query: {
          useSuspenseQuery: false,
        },
        header: (info) => [
          "Generated by orval from the Entropia Manager OpenAPI spec.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
        ],
      },
    },
  },
});
