services:
  front:
    image: ${DOCKERHUB_NAMESPACE:?DOCKERHUB_NAMESPACE is required}/entropia-manager-front:${IMAGE_TAG:-latest}
    container_name: entropia-manager-front
    restart: unless-stopped
    expose:
      - "8019"
    networks:
      - ser5-network

networks:
  ser5-network:
    external: true
