const SYSTEM_USER_ID = process.env.SYSTEM_USER_ID ?? '';
const SYSTEM_USER_PSEUDO = process.env.SYSTEM_USER_PSEUDO ?? '';
const SYSTEM_USER_EMAIL = process.env.SYSTEM_USER_EMAIL ?? '';
const SYSTEM_USER_PASSWORD = process.env.SYSTEM_USER_PASSWORD ?? '';

export { SYSTEM_USER_EMAIL, SYSTEM_USER_ID, SYSTEM_USER_PASSWORD, SYSTEM_USER_PSEUDO };
