###############################################
# BUILD FRONT (React + Vite)
###############################################
FROM node:22-alpine AS build

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste du code
COPY . .

# Build de production Vite
RUN npm run build


###############################################
# SERVEUR NGINX POUR PROD
###############################################
FROM nginx:alpine

# Supprimer la config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copier ta config nginx (reverse proxy API + routing SPA)
COPY nginx.conf /etc/nginx/nginx.conf

# Copier le build React dans nginx
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
