# ---------- BUILD FRONT ----------
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# ---------- NGINX ----------
FROM nginx:alpine

# config nginx custom
COPY nginx.conf /etc/nginx/nginx.conf

# copie du build React
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
