###############################################
# BUILD FRONT (React + Vite)
###############################################
FROM node:22-alpine AS build

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the project files
COPY . .

# Build Vite production bundle
RUN npm run build


###############################################
# NGINX SERVER FOR PRODUCTION
###############################################
FROM nginx:alpine

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx config (reverse proxy + SPA routing)
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the Vite build output into Nginx's static folder
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
