FROM node:24-alpine3.22 AS build
WORKDIR /app/front-end
COPY front-end/package*.json ./
RUN npm ci
COPY front-end/ ./
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
RUN npm run build:docker

FROM node:24-alpine3.22 AS runtime
WORKDIR /app
RUN npm i -g serve
COPY --from=build /app/front-end/dist ./dist
EXPOSE 8019
CMD ["serve", "-s", "dist", "-l", "8019"]
