-- AlterTable
ALTER TABLE "pedcard" ALTER COLUMN "created_at" DROP DEFAULT,
ALTER COLUMN "created_at" SET DATA TYPE TEXT,
ALTER COLUMN "updated_at" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "transaction" ALTER COLUMN "created_at" DROP DEFAULT,
ALTER COLUMN "created_at" SET DATA TYPE TEXT,
ALTER COLUMN "updated_at" SET DATA TYPE TEXT;
