services:
  frontend:
    image: entropia-manager-frontend:${IMAGE_TAG:-latest}
    pull_policy: never
    container_name: entropia-manager-frontend
    expose:
      - "8019"
    restart: unless-stopped
    networks:
      - ser5-network

networks:
  ser5-network:
    external: true
