map $arg_size $img_folder {
    default micro;
    ~*^micro$  micro;
    ~*^normal$ normal;
}

map $arg_size $img_suffix {
    default Micro;
    ~*^micro$  Micro;
    ~*^normal$ Normal;
}

server {
    listen 80;
    server_name entropia-manager;

    location /api/ {
        proxy_pass http://entropia-manager-api:8020;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
location ~ ^/images/([0-9]+)$ {
    set $image_id $1;
    rewrite ^ /images/$img_folder/$image_id$img_suffix.jpg last;
}

    location /images/ {
        alias /em/images/;
        autoindex off;
    }

    location / {
        proxy_pass http://entropia-manager-front:8019;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


