name: Local Continue Config
version: 0.0.1
schema: v1
models:
  - name: Autodetect
    provider: ollama
    model: AUTODETECT
    apiBase: http://192.168.1.47:11434
    roles:
      - chat
      - autocomplete
      - edit
      - apply
      - embed
    capabilities:
      - tool_use
context:
  - provider: tree
  - provider: open
  - provider: file
